Fix compiler errors and warnings, Cleanup main.cpp
- Remove old comments and unused code from main.cpp
- Fix the following compiler errors and warnings (compiles now):

WARNING: main.cpp:64:23: warning: comparison between ‘gameState_t’ {aka ‘enum gameState_t’} and ‘enum menus_t’ if(game.gameState == PAUSE)

WARNING: menu.c:111:9: warning: implicit declaration of function ‘renderSettings’

ERROR: multiple definitions / redefinition of 'int recordsInFile'