Fix Windows no output, Fix Linux ttf undefined errors (cmake)
- in windows .dll files for SDL_TTF were not copied to output due to typo
    resulted in no output at all (e.g. not even printf in main)
- in linux library is called SDL_ttf instead of SDL2_ttf
    resulted in undefined reference to `TTF_Init' etc